### ISSUE TITLE
react-web cannot work on Windows

### ISSUE THREAD

**Issue by jameshen17** [taobaofed/react-web#100]
It seems react-web only can work on Mac, any plan to support Windows OS?

**Comment by yuanyan** [comment]
What problem with windows?

**Comment by jameshen17** [comment]
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contextify package,
npm ERR! not with npm itself.

Nodejs version is 5.11 @ windows

**Comment by mkdotcom** [comment]
You can try running "npm install" from a visual studio command line shell
