### ISSUE TITLE
Module not found，按平台加载对应js失败

### ISSUE THREAD

**Issue by luqin** [taobaofed/react-web#110]
![image](https://cloud.githubusercontent.com/assets/2267688/15568500/d6074b68-235e-11e6-8229-aa9aecc36b79.png)

![image](https://cloud.githubusercontent.com/assets/2267688/15568470/b3b5b888-235e-11e6-9694-8b7b694dc7e5.png)

**Comment by Shawn8585** [comment]
我也加载失败，不知道你是怎么解决的！我在component头上注释中也加了@providesModule Scanner，不知道为何就是加载不到

**Comment by luqin** [comment]
我已经放弃使用了，同步太慢
