### ISSUE TITLE
如何在现有的react native项目中init react-web?

### ISSUE THREAD

**Issue by xiongjianxu** [taobaofed/react-web#111]

**Comment by xiongjianxu** [comment]
如题，单纯的react-web init 会创建一个新项目，而在已有的react native项目中init又会报错。
另外，在执行react-web init  后，npm有warn ,这个是本机的问题吗？
warn如下 : 
npm WARN EPEERINVALID babel-eslint@5.0.4 requires a peer of eslint@<2.3.0 but none was installed.
npm WARN EPEERINVALID react-web@0.2.4 requires a peer of react@~0.14.0 but none was installed.
npm WARN EPEERINVALID react-web@0.2.4 requires a peer of react-dom@~0.14.0 but none was installed.
npm WARN EPEERINVALID react-hot-loader@1.2.7 requires a peer of react@>=0.11.0 but none was installed.
npm WARN EPEERINVALID react-hot-api@0.4.7 requires a peer of react@>=0.11.0 || ^0.14.0-rc but none was installed.

**Comment by luqin** [comment]
自己复制文件配置吧

**Comment by xiongjianxu** [comment]
@luqin 谢谢解答。你的意思是 reac-web init 创建一个新项目，然后复制这个项目到已有的react-native项目目录里面进行配置吗？

**Comment by luqin** [comment]
也是可以的，不过我发现这项目很多组件缺失，而且不知道后续维护度怎么样？

**Comment by yuanyan** [comment]
在已有项目比较推荐手动复制
