### ISSUE TITLE
require适配资源图片问题

### ISSUE THREAD

**Issue by Shawn8585** [taobaofed/react-web#113]
Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)

我在代码中使用了               require('./add.png');
但我实际这张图片有2个尺寸，文件名为 add@1x.png  add@2x.png。这个在android，iOS是可以正常读取的，但在web端就报开头的错。不知道是我用法不对，还是咱们现在就不支持多尺寸适配

**Comment by yuanyan** [comment]
React Web 暂未支持这个特性，需要额外的webpack插件才可以支持
