### ISSUE TITLE
Cannot define 'query' and multiple loaders in loaders list

### ISSUE THREAD

**Issue by feifeipan** [taobaofed/react-web#119]
I run "react-web start",but it shows errors:

 
ERROR  Cannot define 'query' and multiple loaders in loaders list
Error: Cannot define 'query' and multiple loaders in loaders list
    at getLoadersFromObject (/Users/feifeipan/Code/react-native/SampleNavigator2/node_modules/webpack-core/lib/LoadersList.js:54:65)
    at LoadersList.<anonymous> (/Users/feifeipan/Code/react-native/SampleNavigator2/node_modules/webpack-core/lib/LoadersList.js:78:12)
    at Array.map (native)
    at LoadersList.match (/Users/feifeipan/Code/react-native/SampleNavigator2/node_modules/webpack-core/lib/LoadersList.js:70:19)
    at /Users/feifeipan/Code/react-native/SampleNavigator2/node_modules/webpack/lib/NormalModuleFactory.js:111:68
    at /Users/feifeipan/Code/react-native/SampleNavigator2/node_modules/async/lib/async.js:726:13
    at /Users/feifeipan/Code/react-native/SampleNavigator2/node_modules/async/lib/async.js:52:16
    at done (/Users/feifeipan/Code/react-native/SampleNavigator2/node_modules/async/lib/async.js:246:17)
    at /Users/feifeipan/Code/react-native/SampleNavigator2/node_modules/async/lib/async.js:44:16
    at /Users/feifeipan/Code/react-native/SampleNavigator2/node_modules/async/lib/async.js:723:17
    at /Users/feifeipan/Code/react-native/SampleNavigator2/node_modules/async/lib/async.js:167:37
    at /Users/feifeipan/Code/react-native/SampleNavigator2/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:28:24
    at onResolved (/Users/feifeipan/Code/react-native/SampleNavigator2/node_modules/enhanced-resolve/lib/Resolver.js:39:10)
    at /Users/feifeipan/Code/react-native/SampleNavigator2/node_modules/enhanced-resolve/lib/Resolver.js:123:21
    at /Users/feifeipan/Code/react-native/SampleNavigator2/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/Users/feifeipan/Code/react-native/SampleNavigator2/node_modules/enhanced-resolve/lib/Resolver.js:104:30)

**Comment by yuanyan** [comment]
@feifeipan Which version do you use?

**Comment by huhood** [comment]
我用了0.27 也有这问题

**Comment by huhood** [comment]
webpack-config.js module配置如下：

module: {
    loaders: [{
      test: /\.json$/,
      loader: 'json',
    }, {
      test: /\.jsx?$/,
      loaders: 'react-hot',
      include: [config.paths.src],
      exclude: [/node_modules/]
    }, {
      test: /\.jsx?$/,
      loaders: 'babel',
      query: {
        presets: ['es2015', 'react']
      },
      include: [config.paths.src],
      exclude: [/node_modules/]
    }, {
      test: /\.(eot|otf|svg|ttf|woff|woff2|png|jpg|gif)\w*/,
      loader: 'file'
    }]

**Comment by feifeipan** [comment]
@huhood 我找到原因了
原来是：
{
test: /.jsx?$/,
loader: ['babel'],
query: {
presets: ['es2015', 'react']
},
...}

需要改成
{
test: /.jsx?$/,
**loader: 'babel'**,
query: {
presets: ['es2015', 'react']
},
...}

应该是query不能应用在loader数组上。

**Comment by huhood** [comment]
@feifeipan 你看我贴的代码哈，就是 loader: 'babel',

**Comment by huhood** [comment]
@feifeipan 不对，我的是 loaders: 'babel',

**Comment by huhood** [comment]
根据 http://stackoverflow.com/questions/35266706/webpack-error-cannot-define-query-and-multiple-loaders-in-loaders-list 解决方案，将：

> {
      test: /\.jsx?$/,
      loaders: 'babel',
      query: {
        presets: ['es2015', 'react']
      },
      include: [config.paths.src],
      exclude: [/node_modules/]
    },

改为 ：

> {
      test: /\.jsx?$/,
      include: [config.paths.src],
      exclude: /node_modules/,
      loaders: ['babel?presets[]=es2015,presets[]=react,plugins[]=transform-runtime']
    }

又提示另一个错误 

r.forEach is not a function
at /Users/huhood/Desktop/ReactWeb/node_modules/webpack-core/lib/LoadersList.js:81:5

查看了下  源码是 ：

> LoadersList.prototype.match = function match(str) {
	return this.list.map(function(element) {
		if(Array.isArray(element)) {
			for(var i = 0; i < element.length; i++) {
				if(this.matchObject(str, element[i]))
					return getLoadersFromObject(element[i]);
			}
		} else {
			if(this.matchObject(str, element))
				return getLoadersFromObject(element);
		}
	}, this).filter(Boolean).reduce(function(array, r) {
		**r.forEach(function(r) {** // 这里报错
			array.push(r);
		});
		return array;
	}, []) || [];
};

**Comment by yuanyan** [comment]
Try upgrade to 0.3.2
