### ISSUE TITLE
ES6 ... is not supported??

### ISSUE THREAD

**Issue by Creemli** [taobaofed/react-web#12]
When I use react-web to convert my RN project, errors come:

<code><pre>
ERROR in ./app/reducers/counter.js
Module build failed: SyntaxError: /Users/apple/Desktop/FProject/app/reducers/counter.js: Unexpected token (19:16)
  17 |         case types.INCREMENT:
  18 |             return {
> 19 |                 ...state,
     |                 ^
  20 |                 count: state.count + action.num
  21 |             };
  22 |         case types.DECREMENT:

</pre></code>

So how to handle this problem?

**Comment by yuanyan** [comment]
Is the babel rise the error?

**Comment by Creemli** [comment]
I don't know. But I guess maybe the loading sequence issues. 
I try to write the following in your demo:
<code><pre>

var a = {a:1};
var b = {...a, b:1};
console.log(b);

var ReactNativeWebExample = React.createClass({
...
</pre></code>
it also has this problem:
<code><pre>
ERROR in ./index.ios.js
Module build failed: SyntaxError: /Users/apple/Desktop/RN/react-native-web-example/index.ios.js: Unexpected token (18:9)
  16 |
  17 | var a = {a:1};
> 18 | var b = {...a, b:1};
     |          ^
  19 | console.log(b);
  20 |
  21 | var ReactNativeWebExample = React.createClass({
</pre></code>

**Comment by yuanyan** [comment]
@Creemli In react native web example, babel loader not set a ES support level, try set stage option to 1. https://github.com/yuanyan/react-native-web-example/blob/master/web/webpack-dev-server.config.js#L59

**Comment by Creemli** [comment]
Many thanks! fixed~
