### ISSUE TITLE
react-web web端页面空白

### ISSUE THREAD

**Issue by wing3501** [taobaofed/react-web#120]
新建一个react-native项目
ios.index.js如下
![4](https://cloud.githubusercontent.com/assets/14328161/16002125/7a1d364a-3188-11e6-9a3d-ac1882da1e71.png)

webpack.config.js如下
这里修改了'loaders'为'loader'
![5](https://cloud.githubusercontent.com/assets/14328161/16002152/9ea961be-3188-11e6-985a-527181eb113a.png)

package.json如下
![1](https://cloud.githubusercontent.com/assets/14328161/16001875/3598948e-3187-11e6-804e-9f1b4b20936c.png)

执行 npm start
执行 react-web start 也正常
![2](https://cloud.githubusercontent.com/assets/14328161/16002016/efd0d794-3187-11e6-8601-c1908eaf9480.png)

最后展示空白页面
<img width="449" alt="3" src="https://cloud.githubusercontent.com/assets/14328161/16002052/20c464ba-3188-11e6-9c7c-67f68a08cc7e.png">

请问有react-native@27的朋友，有遇到相同的问题吗

**Comment by yuanyan** [comment]
没有任何报错吗？

**Comment by wing3501** [comment]
没有报错。是新建的一个react-native项目

**Comment by feifeipan** [comment]
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  **Platform**
} from 'react-native';

Platform引入了嘛？

**Comment by yuanyan** [comment]
@feifeipan Platform没引入是会报错的吧？

**Comment by yuanyan** [comment]
@wing3501 更新到最新的试试，我看webpack的配置不是最新的 0.3.* 版本

**Comment by wing3501** [comment]
@yuanyan 已解决。就是Platform没引入的问题。也没有报错。非常感谢。

**Comment by feifeipan** [comment]
@yuanyan 是的。
