### ISSUE TITLE
Failed to build DependencyGraph: Naming collision detected: /Users/XXXX/Desktop/ReactWeb/package.json collides with /Users/XXXX/Desktop/ReactWeb/node_modules/react-web/lib/react-web.js

### ISSUE THREAD

**Issue by huhood** [taobaofed/react-web#121]
基于0.3.2版本，项目创建好之后运行 react-web start 报错

Failed to build DependencyGraph: Naming collision detected: /Users/XXXX/Desktop/ReactWeb/package.json collides with /Users/XXXX/Desktop/ReactWeb/node_modules/react-web/lib/react-web.js

**Comment by yuanyan** [comment]
工程名不能是 ReactWeb

**Comment by huhood** [comment]
确实是重名了
