### ISSUE TITLE
生成的bundle.js体积是否能做优化

### ISSUE THREAD

**Issue by feifeipan** [taobaofed/react-web#122]
咨询个问题，目前一个空白项目，bundle.js压缩之后的大小大概在近500K。也就是手机浏览器端要下载近500K的JS。

请问是否有什么办法把体积做优化呢？

谢谢。

**Comment by yuanyan** [comment]
简单的方式可以手工移除没有使用的组件，技术上已知如果使用es6的import与export，babel在打包上能自动识别未使用的，然后移除
