### ISSUE TITLE
第三方组件es5语法导致react-web start 报错

### ISSUE THREAD

**Issue by wing3501** [taobaofed/react-web#124]
已有一个react-native项目，为它添加react-web支持。
执行react-web start 时报错：
错误信息如下：
ERROR in ./~/react-native-scrollable-tab-view/index.js
Module parse failed: /Users/xxxx/Documents/work/XXXX/node_modules/react-native-scrollable-tab-view/index.js Unexpected token (95:13)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (95:13)
    at Parser.pp.raise (/Users/xxxx/Documents/work/XXXX/node_modules/webpack/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.unexpected (/Users/xxxx/Documents/work/XXXX/node_modules/webpack/node_modules/acorn/dist/acorn.js:1490:8)
    at Parser.pp.parseExprAtom (/Users/xxxx/Documents/work/XXXX/node_modules/webpack/node_modules/acorn/dist/acorn.js:333:12)
    at Parser.pp.parseExprSubscripts (/Users/xxxx/Documents/work/XXXX/node_modules/webpack/node_modules/acorn/dist/acorn.js:228:19)
    at Parser.pp.parseMaybeUnary (/Users/xxxx/Documents/work/XXXX/node_modules/webpack/node_modules/acorn/dist/acorn.js:207:17)
    at Parser.pp.parseExprOps (/Users/xxxx/Documents/work/XXXX/node_modules/webpack/node_modules/acorn/dist/acorn.js:154:19)
    at Parser.pp.parseMaybeConditional (/Users/xxxx/Documents/work/XXXX/node_modules/webpack/node_modules/acorn/dist/acorn.js:136:19)

报错的语法文件均来自项目中引用的第三方组件,
有
react-native-scrollable-tab-view
react-native-picker
react-native-swipeout
react-native-modalbox
react-native-viewpager
react-native-qrcode

这些组件，基本上都是es5语法写的,而且都是最新版本。

本机环境：
user-agent = "npm/3.9.5 node/v4.2.6 darwin x64"

项目
package.json
{
  "name": "XXXX",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "file-loader": "^0.8.5",
    "query-string": "^3.0.1",
    "react": "^15.1.0",
    "react-dom": "^15.1.0",
    "react-native": "0.27.2",
    "react-native-actionsheet": "^2.0.1",
    "react-native-communications": "^1.0.1",
    "react-native-device-info": "^0.9.1",
    "react-native-image-picker": "^0.18.4",
    "react-native-location": "^0.14.3",
    "react-native-modalbox": "^1.3.3",
    "react-native-picker": "^3.0.4",
    "react-native-qrcode": "^0.2.2",
    "react-native-scrollable-tab-view": "^0.4.4",
    "react-native-sqlite-storage": "^2.1.4",
    "react-native-swipeout": "^2.0.12",
    "react-native-tab-navigator": "^0.3.2",
    "react-native-vector-icons": "^1.2.1",
    "react-native-viewpager": "^0.2.1",
    "react-web": "0.3.2"
  },
  "devDependencies": {
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-1": "^6.5.0",
    "haste-resolver-webpack-plugin": "^0.2.1",
    "json-loader": "^0.5.4",
    "react-hot-loader": "^1.3.0",
    "webpack": "^1.13.1",
    "webpack-dev-server": "^1.14.1",
    "webpack-html-plugin": "^0.1.1"
  }
}

项目在ios模拟器上运行项目是没有问题的。
请问，这个问题是es5语法导致的吗？除了改第三方组件的源码，还有别的解决办法吗？

**Comment by yuanyan** [comment]
Unexpected token 是什么语法问题？

**Comment by wing3501** [comment]
/Users/xxxx/Documents/work/XXXX/node_modules/react-native-scrollable-tab-view/index.js
如下：
`const React = require('react');
const {
  PropTypes,
} = React;
const ReactNative = require('react-native');
const {
  Dimensions,
  View,
  Animated,
  ScrollView,
  Platform,
  StyleSheet,
  ViewPagerAndroid,
  InteractionManager,
} = ReactNative;
const TimerMixin = require('react-timer-mixin');

const DefaultTabBar = require('./DefaultTabBar');
const ScrollableTabBar = require('./ScrollableTabBar');

const ScrollableTabView = React.createClass({
  mixins: [TimerMixin, ],
  statics: {
    DefaultTabBar,
    ScrollableTabBar,
  },

  propTypes: {
    tabBarPosition: PropTypes.oneOf(['top', 'bottom', 'overlayTop', 'overlayBottom', ]),
    initialPage: PropTypes.number,
    page: PropTypes.number,
    onChangeTab: PropTypes.func,
    onScroll: PropTypes.func,
    renderTabBar: PropTypes.any,
    style: View.propTypes.style,
    contentProps: PropTypes.object,
    scrollWithoutAnimation: PropTypes.bool,
    locked: PropTypes.bool,
  },

  getDefaultProps() {
    return {
      tabBarPosition: 'top',
      initialPage: 0,
      page: -1,
      onChangeTab: () => {},
      onScroll: () => {},
      contentProps: {},
      scrollWithoutAnimation: false,
      locked: false,
    };
  },

  getInitialState() {
    return {
      currentPage: this.props.initialPage,
      scrollValue: new Animated.Value(this.props.initialPage),
      containerWidth: Dimensions.get('window').width,
    };
  },

  componentWillReceiveProps(props) {
    if (props.page >= 0 && props.page !== this.state.currentPage) {
      this.goToPage(props.page);
    }
  },

  goToPage(pageNumber) {
    this.props.onChangeTab({ i: pageNumber, ref: this._children()[pageNumber], });

    if (Platform.OS === 'ios') {
      const offset = pageNumber * this.state.containerWidth;
      if (this.scrollView) {
        this.scrollView.scrollTo({x: offset, y: 0, animated: !this.props.scrollWithoutAnimation, });
      }
    } else {
      if (this.scrollView) {
        if (this.props.scrollWithoutAnimation) {
          this.scrollView.setPageWithoutAnimation(pageNumber);
        } else {
          this.scrollView.setPage(pageNumber);
        }
      }
    }

    this.setState({currentPage: pageNumber, });
  },

  renderTabBar(props) {
    if (this.props.renderTabBar === false) {
      return null;
    } else if (this.props.renderTabBar) {
      return React.cloneElement(this.props.renderTabBar(props), props);
    } else {
      return <DefaultTabBar {...props} />;
    }
  },

  renderScrollableContent() {
    if (Platform.OS === 'ios') {
      return (
        <ScrollView
          horizontal
          pagingEnabled
          automaticallyAdjustContentInsets={false}
          style={styles.scrollableContentIOS}
          contentContainerStyle={styles.scrollableContentContainerIOS}
          contentOffset={{ x: this.props.initialPage * this.state.containerWidth, }}
          ref={(scrollView) => { this.scrollView = scrollView; }}
          onScroll={(e) => {
            const offsetX = e.nativeEvent.contentOffset.x;
            this._updateScrollValue(offsetX / this.state.containerWidth);
          }}
          onMomentumScrollBegin={(e) => {
            const offsetX = e.nativeEvent.contentOffset.x;
            const page = Math.round(offsetX / this.state.containerWidth);
            if (this.state.currentPage !== page) {
              this._updateSelectedPage(page);
            }
          }}
          onMomentumScrollEnd={(e) => {
            const offsetX = e.nativeEvent.contentOffset.x;
            const page = Math.round(offsetX / this.state.containerWidth);
            if (this.state.currentPage !== page) {
              this._updateSelectedPage(page);
            }
          }}
          scrollEventThrottle={16}
          scrollsToTop={false}
          showsHorizontalScrollIndicator={false}
          scrollEnabled={!this.props.locked}
          directionalLockEnabled
          alwaysBounceVertical={false}
          keyboardDismissMode="on-drag"
          {...this.props.contentProps}>
          {this._children().map((child, idx) => {
            return <View
              key={child.props.tabLabel + '_' + idx}
              style={{width: this.state.containerWidth, }}>
              {child}
            </View>;
          })}
        </ScrollView>
      );
    } else {
      return (
        <ViewPagerAndroid
         style={styles.scrollableContentAndroid}
         initialPage={this.props.initialPage}
         onPageSelected={this._updateSelectedPage}
         keyboardDismissMode="on-drag"
         scrollEnabled={!this.props.locked}
         onPageScroll={(e) => {
           const { offset, position, } = e.nativeEvent;
           this._updateScrollValue(position + offset);
         }}
         ref={(scrollView) => { this.scrollView = scrollView; }}
         {...this.props.contentProps}>
         {this._children().map((child, idx) => {
           return <View
             key={child.props.tabLabel + '_' + idx}
             style={{width: this.state.containerWidth, }}>
             {child}
           </View>;
         })}
        </ViewPagerAndroid>
      );
    }
  },

  _updateSelectedPage(currentPage) {
    let localCurrentPage = currentPage;
    if (typeof localCurrentPage === 'object') {
      localCurrentPage = currentPage.nativeEvent.position;
    }
    this.setState({currentPage: localCurrentPage, }, () => {
      this.props.onChangeTab({ i: localCurrentPage, ref: this._children()[localCurrentPage], });
    });
  },

  _updateScrollValue(value) {
    this.state.scrollValue.setValue(value);
    this.props.onScroll(value);
  },

  _handleLayout(e) {
    const { width, } = e.nativeEvent.layout;

    if (width !== this.state.containerWidth) {
      this.setState({ containerWidth: width, });
      this.requestAnimationFrame(() => {
        this.goToPage(this.state.currentPage);
      });
    }
  },

  _children() {
    return React.Children.map(this.props.children, (child) => child);
  },

  render() {
    let overlayTabs = (this.props.tabBarPosition === 'overlayTop' || this.props.tabBarPosition === 'overlayBottom');
    let tabBarProps = {
      goToPage: this.goToPage,
      tabs: this._children().map((child) => child.props.tabLabel),
      activeTab: this.state.currentPage,
      scrollValue: this.state.scrollValue,
      containerWidth: this.state.containerWidth,
    };

    if (this.props.tabBarUnderlineColor) {
      tabBarProps.underlineColor = this.props.tabBarUnderlineColor;
    }
    if (this.props.tabBarBackgroundColor) {
      tabBarProps.backgroundColor = this.props.tabBarBackgroundColor;
    }
    if (this.props.tabBarActiveTextColor) {
      tabBarProps.activeTextColor = this.props.tabBarActiveTextColor;
    }
    if (this.props.tabBarInactiveTextColor) {
      tabBarProps.inactiveTextColor = this.props.tabBarInactiveTextColor;
    }
    if (this.props.tabBarTextStyle) {
      tabBarProps.textStyle = this.props.tabBarTextStyle;
    }
    if (overlayTabs) {
      tabBarProps.style = {
        position: 'absolute',
        left: 0,
        right: 0,
        [this.props.tabBarPosition === 'overlayTop' ? 'top' : 'bottom']: 0,
      };
    }

    return <View style={[styles.container, this.props.style, ]} onLayout={this._handleLayout}>
      {this.props.tabBarPosition === 'top' && this.renderTabBar(tabBarProps)}
      {this.renderScrollableContent()}
      {(this.props.tabBarPosition === 'bottom' || overlayTabs) && this.renderTabBar(tabBarProps)}
    </View>;
  },
});

module.exports = ScrollableTabView;

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollableContentContainerIOS: {
    flex: 1,
  },
  scrollableContentIOS: {
    flexDirection: 'column',
  },
  scrollableContentAndroid: {
    flex: 1,
  },
});
`

**Comment by wing3501** [comment]
我自己用es5写了一个组件倒是没有问题，也不是所有es5组件都不行，应该是个别语法的问题

**Comment by flyskywhy** [comment]
@wing3501 @yuanyan , it's solved in issue #138
