### ISSUE TITLE
能支持Server rendering吗

### ISSUE THREAD

**Issue by eastonqiu** [taobaofed/react-web#127]
请问能支持Server rendering吗

**Comment by yuanyan** [comment]
React支持Server Side Render

**Comment by Beven91** [comment]
React 虽然支持，但是基于React-Web却不能，因为项目中包含了部分浏览器dom以及bom的操作，估计需要针对这几个进行纯node端处理才行

**Comment by mc-zone** [comment]
同问，请问server render 的支持计划是怎样的？
