### ISSUE TITLE
How to run app in browser

### ISSUE THREAD

**Issue by chandu0101** [taobaofed/react-web#13]
is it possible to run app in browser (no mobile simulation .. ) ?

**Comment by akecn** [comment]
if you want run react native app in browser, you can try http://rnplay.org/

**Comment by chandu0101** [comment]
hmm so with react-web we can only build mobile web apps , not ***web*** apps ?

**Comment by chandu0101** [comment]
ca we expect support for browsers in future ? or i have to roll back my deps to https://github.com/necolas/react-native-web again  :s

**Comment by yuanyan** [comment]
@chandu0101  react-web@0.1.2 will support click event, but move event maybe later.

**Comment by chandu0101** [comment]
@yuanyan  thats great news, for my app i just need click event for now. looking forward to new release :)

**Comment by necolas** [comment]
Cool, looks like there is some of react-native-web's code in here.

@chandu0101 so does this work in browsers? what issues you have with react-native-web (apart from missing APIs)? and what do you need 'onClick' for instead of the `Touchable` press events?

**Comment by chandu0101** [comment]
@necolas 
> so does this work in browsers? 

atleast my admin app working fine in chrome .

>what issues you have with react-native-web (apart from missing APIs)

apart from ***missing APIs*** none , for me Navigator API is crucial because i have router(scala.js)  built based on react-native navigator. 

>what do you need 'onClick' for instead of the Touchable press events

i didn't understand this question fully, but we need to support mouse events to run app in desktop browsers! ..

**Comment by necolas** [comment]
> Navigator API is crucial because i have router(scala.js) built based on react-native navigator.

oh interesting, curious to hear more about how that works. do you have your url's defined in the scala.js router code?

> but we need to support mouse events to run app in desktop browsers!

I assumed we'd want `onPress` to fire on mouse clicks. do you think a web version should expose all the react events (`onClick`, `onKeyUp`, etc.) for web environment?

**Comment by chandu0101** [comment]
>oh interesting, curious to hear more about how that works. do you have your url's defined in the scala.js router code?

as mentioned here i don't need valid urls (atleast for my use case/ in my theory) 
https://github.com/necolas/react-native-web/issues/29#issuecomment-145291663
