### ISSUE TITLE
Warning: Unknown props `allowFontScaling`, `accessible`, `isHighlighted` on <span> tag. Remove these props from the element.

### ISSUE THREAD

**Issue by eastonqiu** [taobaofed/react-web#133]
how to fix this warning. thanks.

**Comment by brianneisler** [comment]
Same problem on my end.

**Comment by cssivision** [comment]
<span/> tag not support these props `allowFontScaling`, `accessible`, `isHighlighted` on <span> tag, remove them.

**Comment by wy-ei** [comment]
This means  `<span>` tag don't support those props. 

Do not pass `props` this way:

```jsx
<span {...props}>
    {/*  */}
</span>
```

You should only pass the props that `span` really need:

```jsx
<span
  className={props.className}
  style={props.style}
>
    {/*  */}
</span>
```

**Comment by cssivision** [comment]
for detail https://fb.me/react-unknown-prop
