### ISSUE TITLE
WebView使用时候报错

### ISSUE THREAD

**Issue by poormonkey** [taobaofed/react-web#134]
extendCreateElement.js:15 Uncaught TypeError: Cannot read property 'isReactNativeComponent' of undefined

    if (props && props.style && (Array.isArray(props.style) || _typeof(props.style) === 'object') && type.isReactNativeComponent

请问这个怎么解决，有其他方式在应用内部打开链接吗？

**Comment by brainpoint** [comment]
怎么都没人回应?

**Comment by yuanyan** [comment]
Fix in react-web@0.4.3
