### ISSUE TITLE
react-web start 出现错误

### ISSUE THREAD

**Issue by damly** [taobaofed/react-web#136]
ERROR in Path must be a string. Received undefined

**Comment by brainpoint** [comment]
同问

**Comment by brainpoint** [comment]
react-native 版本号0.30; es2016, 是不是因为这个问题造成的??

**Comment by xnllc** [comment]
同问

**Comment by lee-my** [comment]
遇到过同样的问题，是因为node版本，我从6.x改为4.x就好了

**Comment by brainpoint** [comment]
是否可以使用 node 6.x来start, 因为服务器使用koa, 只能用6.x来启动

**Comment by qussers** [comment]
遇到了相同的问题。。

**Comment by yawetse** [comment]
it's impossible to get it to work with the latest version of react and node 6, use NVM and run react-web start with node 5.x

**Comment by flyskywhy** [comment]
@damly @brainpoint @xnllc @lee-my @qussers @yawetse , according to closed issue https://github.com/webpack/webpack/issues/2463 , it can be resolved by:

    use node 5.x instead of node 6

or

    upgrade to babel-core@6.1x

**Comment by Beven91** [comment]
add a key 'publicPath' to the webpack config  output node
    
  output:{
     publicPath:''
 }

**Comment by ryangun** [comment]
@Beven91 👍

**Comment by flyskywhy** [comment]
@brainpoint , you're right :+1:
