### ISSUE TITLE
Troubles with IE 11 style property flex: 1 1 0px

### ISSUE THREAD

**Issue by mibi-b** [taobaofed/react-web#140]
First thank you for all your hard work on this project.  It has been extremely helpful in keeping one code base and being productive.

I have a simple class that generates a margin.  It does not display in IE 11 but works well in Chrome, Safari, and FireFox.   In ie 11 (version 11.0.9600.18378) the style property that is generated is "flex: 1 1 0px;"  This  0px stops the view from displaying.  If I manually inspect the element and change it to "flex: 1 1 auto" everything works fine.

In chrome the flex style become flex:1 1 0% and displays perfectly.  It also works great in firefox and safari. 

Any ideas on what is going on with IE?
Thank you in advance for your help.
Respectfully,
Bret

Class code (element snapshot below):

```
var hedgeCount = 0;
var _globalWidth = APP.FeedWidth;

export default class marginView extends TimerBaseClass
{
    constructor(props)
    {
      super(props);
      this.props = props;
    }

    static set GlobalWidth(width) {
      _globalWidth = width;
    }

    render()  {
        let key = "marginView" + hedgeCount;
        hedgeCount += 1;
        console.log( "gobalWidth = "  + _globalWidth );
        return (
                <View key={key} style={[styles.container,{width:_globalWidth}]}>
                  <View style={[styles.borderLine,{width:_globalWidth}]}/>
                  <View style={[styles.margin,{width:_globalWidth}]}/>
                </View>
        )
    }

    genStyle() {
      styles = StyleSheet.create({
          container : {
            flex : 1,
            alignItems : 'flex-start',
            flexDirection : 'column',
          },
          borderLine : {
                  backgroundColor : APP.colorGray,
                  height : 1,
          },
          margin : {
                height : 10,
                backgroundColor : APP.colorLightGray,
          },
      });
    }
}

```

Original generated code in IE:
![image](https://cloud.githubusercontent.com/assets/7385373/17464271/f1ff600c-5ca8-11e6-9fb7-79a3eb49a2fb.png)

After changing 0px in flex to auto in IE everything is good.
![image](https://cloud.githubusercontent.com/assets/7385373/17464275/066e453a-5ca9-11e6-8398-53306abc33ff.png)

**Comment by mibi-b** [comment]
One more piece of info if I change the flex property to flex : "1 1 auto"
my margin renders correctly in all browsers.
Any ideas on what syntax I should use for the flex property?
Thank you again,
b

```
genStyle() {
      styles = StyleSheet.create({
          container : {
            **flex : "1 1 auto",**  // this works instead of flex
            alignItems : 'flex-start',
            flexDirection : 'column',
          },
          borderLine : {
                  backgroundColor : APP.colorGray,
                  height : 1,
          },
          margin : {
                height : 10,
                backgroundColor : APP.colorLightGray,
          },
      });

```

**Comment by yuanyan** [comment]
That maybe a bug when use flex: 1 1 0

**Comment by mibi-b** [comment]
Agreed that is the bug in IE.  But where is the best place to handle this?
e.g. Could we put it in a lower level of react-web to check for browser type?

I am handling it like this for now until there is a fix.

```
container: {
             flex : Utils.ieFlex1(), 
              flexDirection : 'column',
              justifyContent: 'center',
              alignItems: 'center',
              backgroundColor : APP.colorWhite, // if not clear text objects will have color
              height : APP.deviceHeight,
              display: APP.FeedWidth + 30 ,
          },
```

Then i have a static function:

 ```
   static ieFlex1() {
      if ( !ieChecked ) {
          Utils.isIE();
          if ( ieTrue ) {
            console.log("RUNNING IN IE");
          }
      }
      return (ieTrue > 0) ? "1 1 auto" : 1 ;
    }
```

But I am hoping that we may hide this code in react-web and just use flex :1 

Thank you again for your help.
