### ISSUE TITLE
bundle.js 是否可以在生成时拆分

### ISSUE THREAD

**Issue by brainpoint** [taobaofed/react-web#142]
系统生产的bundle.js比较大, 压缩了还是很大, 是否可以拆分成几个小文件, 怎么做?

**Comment by yuanyan** [comment]
依赖比较多的原因，且React本身也不小，所以bundle比较大

**Comment by Zephyr-Trail** [comment]
问好，想问一下，在react-web项目中想用页面的一部分展示现有网页（包括url页面和assets html）内容，就如react- native中的WebView，应如何处理？

**Comment by brainpoint** [comment]
webview react-web中好像没有, 我是用react的dangerouslySetInnerHTML来显示, 但是要解决跨域等问题

**Comment by lijax** [comment]
把webview换成iframe就可以了
