### ISSUE TITLE
scrollView 如何获取当前offset位置

### ISSUE THREAD

**Issue by brainpoint** [taobaofed/react-web#144]
在ios/android可使用
`onScroll(evt) {
    evt.nativeEvent.contentOffset.y;
  }`
来获取, web上不行

**Comment by edoohwang** [comment]
请问解决了吗

**Comment by brainpoint** [comment]
ScrollView.web.js 中 修改如下代码:
`  handleScroll(e: Event) {
    if (!this._scrollViewDom)
      this._scrollViewDom = ReactDOM.findDOMNode(this.refs[SCROLLVIEW]);

    e.nativeEvent = e.nativeEvent || {};
    e.nativeEvent.contentOffset = {x:this._scrollViewDom.scrollLeft, y:this._scrollViewDom.scrollTop};

    this.props.onScroll && this.props.onScroll(e);
  }`
