### ISSUE TITLE
some folders miss after react-web init <projectName>

### ISSUE THREAD

**Issue by leonardgithub** [taobaofed/react-web#148]
Happen time: just near the time I submit this issue

only node_modules, package.json and web in the project folder, the below files or folders miss:
├── README.md
├── android/
├── index.android.js
├── index.ios.js
├── ios/

environmental info:
OS: Ubuntu 16.04

$ react-web -v
react-web-cli: 0.0.3
react-web: 0.3.2

**Comment by yuanyan** [comment]
Not tested on ubuntu system, could u find what’s make the problem？

**Comment by flyskywhy** [comment]
@leonardgithub ,react-web init worked well on my Ubuntu 16.04.

By the way, what's your projectName spell?

**Comment by leonardgithub** [comment]
@flyskywhy just a placeholder for my project name

**Comment by flyskywhy** [comment]
@leonardgithub , as you can see in https://github.com/soliury/noder-react-native/commit/21c4a20fbab67f1b4102f6f8899b45258bf9b091 , because `-` is illegal in `react-native init` or `react-web init`, I `npm install -g react-web-cli; cd ..; mv noder-react-native noder; react-web init noder; mv noder noder-react-native` and all worked well, so maybe this issue #148 was caused by your project name?

**Comment by leonardgithub** [comment]
leonard@leonard-g400:~/test$ react-web init myproject
This will walk you through creating a new React Web project in /home/leonard/test/myproject
Installing react-web package from npm...
Setting up new React Web app in /home/leonard/test/myproject
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "" "--save-dev" "webpack@1.13.2" "webpack-dev-server@1.16.1" "babel-loader@6.2.5" "json-loader@0.5.4" "react-hot-loader@1.3.0" "haste-resolver-webpack-plugin@0.2.1" "webpack-html-plugin@0.1.1" "babel-preset-es2015@undefined" "babel-preset-react@undefined" "babel-preset-stage-1@6.16.0"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5

npm ERR! No compatible version found: babel-preset-react@undefined
npm ERR! Valid install targets:
npm ERR! 6.16.0, 6.11.1, 6.11.0, 6.5.0, 6.5.0-1, 6.3.13, 6.2.4, 6.1.18, 6.1.17, 6.1.4, 6.1.2, 6.0.15, 6.0.14, 6.0.12, 6.0.2
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/leonard/test/myproject/npm-debug.log
`npm install` failed
leonard@leonard-g400:~/test$ react-web -v
react-web-cli: 0.0.3
react-web: n/a - not inside a React Web project directory

**Comment by flyskywhy** [comment]
@leonardgithub , `babel-preset-react@undefined` error was solved in bca8e6f3c6e6be0244d12e69b13fde9f4e4a1b63 at 2016-10-09 just after you report this issue, and the latest react-web 0.4.3 contain this commit, so you just need `react-web init myproject` again to get the latest react-web.

plus: `react-web -v` should invoked in `~/test/myproject/` not `~/test/`

btw: Is this issue `some folders miss after react-web init` solved?

**Comment by leonardgithub** [comment]
@flyskywhy OK, I will try. It's so kind of you.
