### ISSUE TITLE
what is the difference between react-native-web and react-web

### ISSUE THREAD

**Issue by leonardgithub** [taobaofed/react-web#149]
react-native-web: 
[https://github.com/necolas/react-native-web](https://github.com/necolas/react-native-web)

**Comment by yuanyan** [comment]
React Web is more react-native then react-native-web, aha!

**Comment by leonardgithub** [comment]
@yuanyan yes, I agree with you!

**Comment by leonardgithub** [comment]
@yuanyan 
Do you know the reason about [https://github.com/taobaofed/react-web/issues/148](https://github.com/taobaofed/react-web/issues/148)?

**Comment by remon-georgy** [comment]
I believe a more elaborate answer would help new developers to pick the right library. Being "more native than react-native-web" got me interested, though!
