### ISSUE TITLE
can you require react-web components in a react-native-web project?

### ISSUE THREAD

**Issue by faceyspacey** [taobaofed/react-web#158]
i.e. the "Haste Way":

```
var View = require('ReactView');
```

react-web has a lot more components than react-native-web, but react-native-web seems to be picking up more steam. It doesn't seem like anyone has time to merge the 2 projects, but perhaps on the component level a shared interface or mechanism could be built to use components between the two.

**Comment by yuanyan** [comment]
We will try, make it better and better.
