### ISSUE TITLE
使用haste-resolver-webpack-plugin出错

### ISSUE THREAD

**Issue by Shaodaxia111** [taobaofed/react-web#164]
webpack.config.js
使用haste-resolver-webpack-plugin配置如下：
var HasteResolverPlugin = require('haste-resolver-webpack-plugin');
 new HasteResolverPlugin({
      platform: 'web',
      nodeModules: ['react-web']
    })
报出如下错误：
ERROR in ./~/react-web/package.json
Module parse failed: /Users/shaopengfei/Desktop/work/demo03/node_modules/react-web/package.json Unexpected token (2:9)

**Comment by Shaodaxia111** [comment]
当配置nodeModules: ['react-web']时，报错。请教一下此问题是因为什么导致的，又该怎么去解决。谢谢

**Comment by Shaodaxia111** [comment]
已解决，谢谢。

**Comment by flyskywhy** [comment]
我没碰到过这个问题，而我发现也还有其他人碰到过 https://github.com/yuanyan/haste-resolver-webpack-plugin/issues/1 ，所以我很好奇这个问题是怎么发生的？@Shaodaxia111 你又是如何解决的？

**Comment by yuanyan** [comment]
是不是install的时候没有安装在项目的node_modules下？
