### ISSUE TITLE
v0.4.1 react-web init error

### ISSUE THREAD

**Issue by TyrealGray** [taobaofed/react-web#170]
$ react-web init RN4Web

This will walk you through creating a new React Web project in /Users/tyrealgray/RN4Web
Installing react-web package from npm...
Setting up new React Web app in /Users/tyrealgray/RN4Web
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "" "--save-dev" "webpack@1.13.2" "webpack-dev-server@1.16.1" "babel-loader@6.2.5" "json-loader@0.5.4" "react-hot-loader@1.3.0" "haste-resolver-webpack-plugin@0.2.1" "webpack-html-plugin@0.1.1" "babel-preset-es2015@undefined" "babel-preset-react@undefined" "babel-preset-stage-1@6.16.0"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: babel-preset-es2015@'undefined'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["6.0.2","6.0.8","6.0.11","6.0.12","6.0.14","6.0.15","6.1.2","6.1.4","6.1.17","6.1.18","6.2.4","6.3.13","6.5.0","6.5.0-1","6.6.0","6.9.0","6.13.0","6.13.1","6.13.2","6.14.0","6.16.0"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'RN4Web'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tyrealgray/RN4Web/npm-debug.log
`npm install` failed

$ react-web -v
react-web-cli: 0.0.3

**Comment by ezioruan** [comment]
the same to me

**Comment by TyrealGray** [comment]
It was fine at version 0.3.2, but something goes wrong when they update and didn't test the cmd line.
If I edit devDependencies in package.json by myself and install, it still could work.

**Comment by yuanyan** [comment]
Fixed in react-web@0.4.2 @TyrealGray @ezioruan
