### ISSUE TITLE
Module not found: Error: Cannot resolve module 'react-dom' 

### ISSUE THREAD

**Issue by IZHQT** [taobaofed/react-web#175]
我按照官方的操作步骤进行配置但是却报了这个问题，不知道是什么问题引起的？

**Comment by flyskywhy** [comment]
如 react-web/package.json 中所说，react 和 react-dom 都属于 peerDependencies ，因为 [peerDependencies 的特性] (https://www.zfanw.com/blog/peerdependencies.html)，所以你需要单独再安装：

    npm install react react-dom --save
