### ISSUE TITLE
ERROR in Path must be a string. Received undefined

### ISSUE THREAD

**Issue by IZHQT** [taobaofed/react-web#176]
启动后，报这个错误，不只是是不是webpack的配置文件出错了，但是配置文件有没有Path这个变量

**Comment by sduqlsc** [comment]
@IZHQT 参考 [https://github.com/taobaofed/react-web/issues/136](url)

**Comment by IZHQT** [comment]
@sduqlsc 页面不存在404

**Comment by sduqlsc** [comment]
@IZHQT 已修改，请参考是不是这个问题。
