### ISSUE TITLE
make react-web global styles more explicit

### ISSUE THREAD

**Issue by chandu0101** [taobaofed/react-web#18]
currently every div under root class has flexbox properties

```
.react-web-root div {
    position: relative;
    box-sizing: border-box;
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -webkit-flex-direction: column;
    -ms-flex-direction: column;
    flex-direction: column;
}
```
if we use third party components(example : react-select) then its breaking third party component layout.

can we add a class tag  `.react-web-view`  to all  `View` components and define global styles for that ?

**Comment by yuanyan** [comment]
Work in progress now.

**Comment by chandu0101** [comment]
:+1:

**Comment by yuanyan** [comment]
@chandu0101 The react-web@0.1.3 change `.react-web-root div` to `.react-root .react-view`.

**Comment by chandu0101** [comment]
excellent thank you . my select box is happy now ;)
