### ISSUE TITLE
ListView大数据量时，性能变得极其弱

### ISSUE THREAD

**Issue by Shaodaxia111** [taobaofed/react-web#182]
你好，是这样的，我最近写了一个一个项目，在用到了listView时，我用大约200组列表数据做测试，在页面滑动至大约150组的时候，页面变的滑动及其缓慢，而且较卡。

期待回复。谢谢！

**Comment by yuanyan** [comment]
Web下ListView的组件尽可能继承PureComponent试下

**Comment by Shaodaxia111** [comment]
好的，谢谢。
