### ISSUE TITLE
如何识别当前页面的url地址？

### ISSUE THREAD

**Issue by sduqlsc** [taobaofed/react-web#183]
如题，如果运行在微信中，然后某个页面需要调用微信菜单的“用浏览器打开”，这时打开的都是类似“http://ip:3000/?xxxx”的地址，界面也只是初始页而不是想要的页面。

**Comment by yuanyan** [comment]
判断当前环境是web，通过浏览器的location可以知道当前url

**Comment by sduqlsc** [comment]
没有表述清楚，问错地方了，用了Navigator与redux，页面地址都变成了http://localhost:3000/#/?_k=0n3h6u。

**Comment by brainpoint** [comment]
使用 history来判断, 地址#/?xxx 是navigator中用了hashHistory造成的

**Comment by sduqlsc** [comment]
@brainpoint 非常感谢，我试试看。

**Comment by sduqlsc** [comment]
@yuanyan navigator中的实现可以换成browserHistory么？

**Comment by cssivision** [comment]
navigator 的实现是尽量和 react-native 保持一致，redux 有对应的 props 可以设置 browserHistory
