### ISSUE TITLE
发现点问题

### ISSUE THREAD

**Issue by unakayou** [taobaofed/react-web#184]
1.rendeRow 回传的sectionID,rowID是字符串，不是数字。
2.propTypes ： Text.propTypes.style 找不到。
3.textInput长度貌似有个最小值？
4. DeviceEventEmitter react-web 是不是没有实现？

**Comment by yuanyan** [comment]
1. 第个问题看下能否PR
2. 没有 Text.propTypes.style  
3. 最小值指的是哪个属性？
4. DeviceEventEmitter 当前什么场景下需要使用？
