### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by bendikl** [taobaofed/react-web#185]
The demo at http://taobaofed.github.io/react-web/ is not working. Please revise what is giving errors so people actually can test your demo.

**Comment by brianneisler** [comment]
I had the same problem. Put together an example project as a template for getting a new project off the ground. https://github.com/brianneisler/react-web-example

**Comment by cssivision** [comment]
@bendikl what the error message? or you can use [example project](https://github.com/brianneisler/react-web-example) as a start
