### ISSUE TITLE
How to use the React web will React Native automatically generate the corresponding packaging web project

### ISSUE THREAD

**Issue by sunnyvalue** [taobaofed/react-web#19]
How to use the React web will React Native automatically generate the corresponding packaging web project ？

As you konw, I created a react native project, and completed the corresponding interface, can be run on the iOS simulator. I have read the react web documents, and made a part of the configuration, I downloaded the "react - native - web - example"(I can run in iOS simulator),  but how do I use reactweb generate corresponding web project, so I can apply the same set of deployment on the web, please help me ,very very thanks...

**Comment by yuanyan** [comment]
Check the latest readme of the [react-native-web-example](https://github.com/yuanyan/react-native-web-example/blob/master/README.md). Try `npm run web-bundle`, it works.

**Comment by Tiagojdferreira** [comment]
@yuanyan Just started a fresh react-native project using the cli. Ran it on the iOS simulator and it runs fine. Added react-web using the CLI and got no errors. When I run the app using ```react-web start``` I get an empty white page at 0.0.0.0:3000. 

Any idea why? There is no error on the console, nor on the terminal, so I am not sure how to debug from here.
