### ISSUE TITLE
新手 跑起来了 但是浏览器中什么都看不到

### ISSUE THREAD

**Issue by shiwenwen** [taobaofed/react-web#190]
如题 新手 跑起来了 但是浏览器中什么都看不到 打开控制台显示TypeError: undefined is not an object (evaluating '_reactNative.StyleSheet.create')

**Comment by cssivision** [comment]
配置文件问题，或者代码问题，你可以把配置文件和demo 贴出来看下

**Comment by cssivision** [comment]
可以使用这个作为模板 https://github.com/brianneisler/react-web-example
