### ISSUE TITLE
关于本地调试的跨域问题

### ISSUE THREAD

**Issue by guojie1689** [taobaofed/react-web#191]
请问在本地调试时候，在webpack.config.js中配置devServer不起作用呢？是否支持？
devServer: {
    proxy: {
      '/sycee/': {
        target: 'http://211.103.153.109:2000',
        secure: false,
        bypass: function(req, res, proxyOptions) {
            console.log('proxy for browser request.'+ req );
        }
      }
    }
  },

**Comment by cssivision** [comment]
暂不支持跨域，你可以在服务器上自行支持跨域。
