### ISSUE TITLE
为什么没有Button这个组件呀？

### ISSUE THREAD

**Issue by Beven91** [taobaofed/react-web#200]
React-native有Button这个控件，请问为什么不考虑实现这个组件呢？

**Comment by buhe** [comment]
rn 也没有 button ,只有 touchableXXX.

**Comment by cssivision** [comment]
react-native has [Button](http://facebook.github.io/react-native/docs/button.html)

**Comment by buhe** [comment]
@cssivision rn 0.36 才有的 button ，而且其实并没有什么用，只是上手容易点而已
