### ISSUE TITLE
Module not found: Error: Cannot resolve module 'react/lib/ReactMount'

### ISSUE THREAD

**Issue by flyjennyetn** [taobaofed/react-web#211]
ERROR in ./index.web.js
Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in E:\wamp
\www\React\rn
 @ ./index.web.js 1:289-320

ERROR in ./~/react-web/Libraries/Animated/Animated.web.js
Module not found: Error: Cannot resolve module 'react/lib/CSSPropertyOperations'
 in E:\wamp\www\React\rn\node_modules\react-web\Libraries\Animated
 @ ./~/react-web/Libraries/Animated/Animated.web.js 14:27-69

ERROR in ./~/react-web/Libraries/PanResponder/injectResponderEventPlugin.web.js
Module not found: Error: Cannot resolve module 'react/lib/EventPluginRegistry' i
n E:\wamp\www\React\rn\node_modules\react-web\Libraries\PanResponder
 @ ./~/react-web/Libraries/PanResponder/injectResponderEventPlugin.web.js 8:25-6
5

ERROR in ./~/react-web/Libraries/PanResponder/injectResponderEventPlugin.web.js
Module not found: Error: Cannot resolve module 'react/lib/ResponderEventPlugin'
in E:\wamp\www\React\rn\node_modules\react-web\Libraries\PanResponder
 @ ./~/react-web/Libraries/PanResponder/injectResponderEventPlugin.web.js 9:26-6
7

ERROR in ./~/react-web/Libraries/PanResponder/injectResponderEventPlugin.web.js
Module not found: Error: Cannot resolve module 'react/lib/EventConstants' in E:\
wamp\www\React\rn\node_modules\react-web\Libraries\PanResponder
 @ ./~/react-web/Libraries/PanResponder/injectResponderEventPlugin.web.js 10:20-
55

ERROR in ./~/react-web/Libraries/PanResponder/injectResponderEventPlugin.web.js
Module not found: Error: Cannot resolve module 'react/lib/ResponderTouchHistoryS
tore' in E:\wamp\www\React\rn\node_modules\react-web\Libraries\PanResponder
 @ ./~/react-web/Libraries/PanResponder/injectResponderEventPlugin.web.js 11:32-
79

ERROR in ./~/react-web/Libraries/Utilties/setNativeProps.web.js
Module not found: Error: Cannot resolve module 'react/lib/CSSPropertyOperations'
 in E:\wamp\www\React\rn\node_modules\react-web\Libraries\Utilties
 @ ./~/react-web/Libraries/Utilties/setNativeProps.web.js 8:26-68

请问 react-web 有QQ群吗？  想找个能交流的地方有吗

**Comment by flyjennyetn** [comment]
自己解决了  

![image](https://cloud.githubusercontent.com/assets/12065761/21217077/49e71f1a-c2e5-11e6-991e-5d2e44c5fee4.png)

**Comment by craone** [comment]
`
var alias = {'react-native':'ReactWeb'};
var missingLib = [
  "CSSPropertyOperations",
  "EventPluginRegistry",
  "ResponderEventPlugin",
  "EventConstants",
  "ResponderTouchHistoryStore"
];

missingLib.forEach(function(filename){
	alias['react/lib/'+filename] = path.join(__dirname,"../node_modules/react-dom/lib/",filename);
});

var webpackConfig = {
  ip: IP,
  port: PORT,
  devtool: 'cheap-module-eval-source-map',
  resolve: {
    alias:alias,
    extensions: ['', '.js', '.web.js', '.ios.js', '.android.js', '.native.js', '.jsx'],
  },
  entry: isProd ? [
    config.paths.index
  ] : [
    'webpack-dev-server/client?http://' + IP + ':' + PORT,
    'webpack/hot/only-dev-server',
    config.paths.index,
  ],
  output: {
  	publicPath:'',// Fix:Path must be a string. Received undefined.
    path: path.join(__dirname, 'output'),
    filename: 'bundle.js'
  },
`
package.json
`
{
  "name": "HelloworldProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "webserver": "node node_modules/react-web/local-cli/cli.js start",
    "bundle": "node node_modules/react-web/local-cli/cli.js bundle"
  },
  "dependencies": {
    "react": "15.4.1",
    "react-native": "0.39.2",
    "react-dom": "15.4.1",
    "react-web": "0.4.5"
  },
  "devDependencies": {
    "babel-jest": "18.0.0",
    "babel-loader": "^6.2.5",
    "babel-preset-react-native": "^1.9.0",
    "babel-preset-stage-1": "^6.16.0",
    "haste-resolver-webpack-plugin": "^0.2.2",
    "jest": "18.0.0",
    "json-loader": "^0.5.4",
    "react-hot-loader": "^1.3.0",
    "react-test-renderer": "15.4.1",
    "webpack": "^1.13.2",
    "webpack-dev-server": "^1.16.1",
    "webpack-html-plugin": "^0.1.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

**Comment by flyjennyetn** [comment]
@craone    extensions: ['', '.js', '.web.js', '.ios.js', '.android.js', '.native.js', '.jsx'], 放到  alias 里面

react-web  感觉已经没有维护了 ，问题很多，我已经放弃了，在用react-native-web

**Comment by craone** [comment]
@flyjennyetn 我也发现了一大堆问题，react-native-web怎么样呀兄弟？有什么建议？

**Comment by flyjennyetn** [comment]
@craone   暂时感觉还不错  可以共同学习进步

**Comment by qlphsk** [comment]
楼主，跟你一样，没办法解决啊

**Comment by cssivision** [comment]
fix https://github.com/taobaofed/react-web/pull/224

**Comment by cssivision** [comment]
由于项目使用了 react, react-dom lib 目录下的文件，因此需要使用固定的版本，不然可能会报错。

**Comment by liuruizhe728** [comment]
taobaofed
