### ISSUE TITLE
Can not response onPress event on Touchable*

### ISSUE THREAD

**Issue by gripleaf** [taobaofed/react-web#215]
I just clone the https://github.com/taobaofed/demo/
And I set up it by run "npm install"(I have already install react-web-cli). When I first try to run it, it came out error like "Can't found CSSPropertyOperations (or EventPluginRegistry, ResponderEventPlugin etc.)". So, I added some following code in web/webpack.config.js.
```
web/webpack.config.js
....
  var alias = {
       'react-native': 'react-web',
        'ReactNativeART': 'react-art',
  };
  ["CSSPropertyOperations","EventPluginRegistry","ResponderEventPlugin", "EventConstants","ResponderTouchHistoryStore    " ].forEach(function(filename){
      alias["react/lib/"+filename] = path.join(__dirname, "../node_modules/react-dom/lib", filename);
  });
module.exports = {
....
    alias: alias
....
}
```

Then I run "react-web start" again, the demo could run well without any error message.
However, the following code in my index.web.js can not work.
```
         <TouchableHighlight onPress={()=>{
              console.log("hello world");
          }}>
          <Text style={styles.welcome}>
            Welcome to React Web!
          </Text>
          </TouchableHighlight>
```
## **When I touch the Text "Welcome to React Web!", the console do not print any message.**

Following is my environment:
node: v5.3.0
npm: 3.3.12
react-native-cli: 2.0.1
react-native: 0.19.0
react-web-cli: 0.0.4
react-web: 0.2.5

**Comment by WeweTom** [comment]
same problem

**Comment by gripleaf** [comment]
I finally do not solve this problem. But, I try another way to achieve my goal.
I install react-native-web in react-native project instead. Then re-config the web/webpack.config.js file like here.
Maybe you can have a try. ^_^

**Comment by WeweTom** [comment]
@gripleaf thanks , I'll have a try

**Comment by cssivision** [comment]
@gripleaf you can use [this](https://github.com/brianneisler/react-web-example) as a project templete, and do not have to re-config the webpack.config.js

**Comment by cssivision** [comment]
fix re-config webpack.config.js problem in https://github.com/taobaofed/react-web/pull/224
