### ISSUE TITLE
新手！start成功，但是页面是空白的，浏览器控制台报错，提示：Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by wjm117** [taobaofed/react-web#219]
1.我的webpack.config配置
![image](https://cloud.githubusercontent.com/assets/20735485/23048660/57f5a6c8-f4f2-11e6-9e0d-b6635a311620.png)

![image](https://cloud.githubusercontent.com/assets/20735485/23048632/2296b09e-f4f2-11e6-9188-4062bc37428f.png)

2.控制台运行react-web start 提示成功，但是打开页面是空白的。浏览器控制台报错提示：Uncaught SyntaxError: Unexpected token import。
  请问这个需要这么解决，谢谢
![image](https://cloud.githubusercontent.com/assets/20735485/22964205/5a5fc210-f392-11e6-98a6-5d8721a4488c.png)

**Comment by cssivision** [comment]
这个属于代码打包编译出错，你把代码贴出来看看

**Comment by wjm117** [comment]
1.index.web.js配置如下：
![image](https://cloud.githubusercontent.com/assets/20735485/23006834/42cd6e38-f43f-11e6-9071-0e618918cb0e.png)

2.setup.js配置如下：
![image](https://cloud.githubusercontent.com/assets/20735485/23006873/699a8186-f43f-11e6-909f-c89599f27a87.png)


3.app.js配置如下：
![image](https://cloud.githubusercontent.com/assets/20735485/23006889/7fc254fc-f43f-11e6-8877-0ca89a31b3d8.png)


原本公司只想做app，但是现在说移动端web也要，想试试看有没有办法把原来的rn项目转web，但是发现这些坑有点难跨……

**Comment by cssivision** [comment]
这个是 webpack 的配置导致产生的问题，你把 web/webpack.config.js 文件贴出来看看

**Comment by wy-ei** [comment]
@cssivision 他在上面已经贴过 webpack 的配置文件了。

**Comment by cssivision** [comment]
你可以使用这个作为项目模板 https://github.com/brianneisler/react-web-example
