### ISSUE TITLE
start 成功，页面空白，无报错

### ISSUE THREAD

**Issue by wjm117** [taobaofed/react-web#222]
1.start成功后打开页面是空白的，控制台如下，好像也正常，但是没内容，请问这是啥情况。
![image](https://cloud.githubusercontent.com/assets/20735485/23118102/e5a8226e-f78d-11e6-9268-db82ab8e11f4.png)
2.react-root可以出来，但是react-view之后就是空的
![image](https://cloud.githubusercontent.com/assets/20735485/23119068/9e2671f8-f791-11e6-98d6-2a7c77987785.png)

3.原来的Unexpected token import报错应该是我们项目使用了极光推送造成的，去掉极光推送功能不再报错，但是还是没内容

**Comment by wjm117** [comment]
1

**Comment by cssivision** [comment]
把项目的代码和webpack 配置贴出来看下

**Comment by wjm117** [comment]
@cssivision 
1.webpack配置：
![image](https://cloud.githubusercontent.com/assets/20735485/23147946/c5c84ccc-f81d-11e6-9ed0-0fac71ba2b23.png)
![image](https://cloud.githubusercontent.com/assets/20735485/23147955/d26188ea-f81d-11e6-93dd-637df1c122b5.png)
2.index.ios配置：
![image](https://cloud.githubusercontent.com/assets/20735485/23147978/f365dd70-f81d-11e6-954a-ec06a2c1ebfe.png)
3.启动文件setup配置：
![image](https://cloud.githubusercontent.com/assets/20735485/23147988/0b626146-f81e-11e6-902b-9f9a688da2d9.png)
