### ISSUE TITLE
我打算翻译reactweb到标准的html tag，引用到github.com/xueduany/react-mix里面，不知道是否可以?

### ISSUE THREAD

**Issue by xueduany** [taobaofed/react-web#23]
现在安卓版本的兼容程度如何？另外对于listview对应h5版本 他们那个缓冲处理 你们是完全一致还是没做？

**Comment by yuanyan** [comment]
React Web里的Listview在功能上与React Native几乎完全一致，原因是Listview组件在React Native里是CustomComponent，所以我们几乎是复用了原有代码进行修改

**Comment by xueduany** [comment]
恩 我的意思是，类似listview这种 你们已经做好了h5的兼容吗？
