### ISSUE TITLE
有段英文看不懂，能解释下吗？

### ISSUE THREAD

**Issue by yy7054wyq5** [taobaofed/react-web#231]
Execute react-web init <ExistedProjectDir> to install stable npm version, or execute react-web init --version git+https://github.com/taobaofed/react-web.git <ExistedProjectDir> to install latest git version. That install react-web and devDependencies to your project and make a web directory with webpack.config.js file under your project
我知道是安装react-web依赖，在项目目录下创建web文件夹，然后在该文件夹下创建webpack.config.js
至于前面写的，安装稳定的npm，还有init命令，实在不能理解。

**Comment by cssivision** [comment]
执行 `react-web init` 安装稳定版本的 react-web，或者执行 `react-web init --version git+https://github.com/taobaofed/react-web.git` 安装最新版本的 react-web，同时在项目里面安装开发依赖，项目目录下创建web文件夹，然后在该文件夹下创建webpack.config.js 文件。

以上。

**Comment by yy7054wyq5** [comment]
3Q

**Comment by cssivision** [comment]
https://github.com/brianneisler/react-web-example 直接使用这个项目作为模板修改
