### ISSUE TITLE
使用react-web init 的项目只有两个文件夹。

### ISSUE THREAD

**Issue by chuyinweilai** [taobaofed/react-web#260]
生成的项目只有node_module和web两个文件夹，以及package.json， package-lock.json两个文件。
这是正常的嘛？我跟着流程走了好几遍都不行

**Comment by cpunion** [comment]
正常的，添加一个 index.ios.js，运行 `react-web start`就可以了。

**Comment by yuanyan** [comment]
可以更新到最新的 1.x 版本
