### ISSUE TITLE
渲染出web页面后title标签如何随页面跳转

### ISSUE THREAD

**Issue by xiamingyu** [taobaofed/react-web#266]
![image](https://user-images.githubusercontent.com/10458215/32413478-9db0bd30-c1d7-11e7-899e-2c632c95c10e.png)

**Comment by xiamingyu** [comment]
貌似好像只能在这里面修改下title，如果通过路由跳转，title不会变化

**Comment by cpunion** [comment]
https://github.com/gaearon/react-document-title

**Comment by xiamingyu** [comment]
document.title动态修改就行了
