### ISSUE TITLE
我去研究一下了代码，copy了listview和navigator过来，先说listview，我看了源代码api到是实现了，但是native的listview有个懒加载的功能，这个没实现啊？你们打算实现吗？不做的话，我就自己做了？

### ISSUE THREAD

**Issue by xueduany** [taobaofed/react-web#27]
到时候可以反馈给你们，我就删除少量的import引用，大部分代码直接抄过来的，我主要是想实现listview的懒加载功能，如果有现成的我就直接抄了，还望赐教。。。。如果大家都没计划写的话，h5这部分listview我还是自己做了算了

**Comment by yuanyan** [comment]
@xueduany 你说的API实现了是指哪个API？懒加载功能是指?

**Comment by yuanyan** [comment]
@xueduany 你说的API实现了是指哪个API？懒加载功能是指?

**Comment by yuanyan** [comment]
@xueduany 你说的API实现了是指哪个API？懒加载功能是指?

**Comment by xueduany** [comment]
在rn里面当listview的array超过30个的时候，只渲染头30行的内容会在下滑快到底的时候，判断是否有剩余内容，每次渲染5个，这样的懒加载处理

**Comment by xueduany** [comment]
再复杂的一点的设计是，对于之前屏幕的内容，统一放进一个替换容器visibility，内容转成string，去掉dom节点的length

**Comment by xueduany** [comment]
navigator的问题，我今天看了代码，我的感觉是其实没有必要实现navios，其实就按照他的navigator模型实现以下基本的history管理就好了，我感觉你们做复杂了，不打算copy navigator代码了，listview我感觉不错，打算帮优化一下，实现一下懒加载

**Comment by yuanyan** [comment]
@xueduany Navigator与ListView几乎是RN原版的代码，我们只是简单修改适配了Web的场景

**Comment by xueduany** [comment]
我知道 应该是和nodemodule的代码翻译了一遍，那部分懒加载是oc代码里面做的，所以单纯的翻译js只能做到兼容，没有100%实现功能

**Comment by yuanyan** [comment]
@xueduany 热情邀请PR，哈哈
