### ISSUE TITLE
Image not displayed when use the images in IOS image.xcassets,how to handle this?

### ISSUE THREAD

**Issue by Creemli** [taobaofed/react-web#28]
If I add the image to image.xcassets, and show it with the code
<code><pre>
&lt;Image style={[{height: 50, width: 80}]} source={{ uri:'test', isStatic: true }} /&gt;
</pre></code>

after transformed by react-web, it turns out to be 
&lt;img src="test"&gt;

and the props of the image doesn't have a base64 image as the other images which used in the way: <code>{Image src={require('../test.png')}}</code>

**Comment by akecn** [comment]
as of 0.14.0 release,  react-native recommend a unified way to manage static image resources.

```
<Image source={require('./my-icon.png')} />
```

http://facebook.github.io/react-native/docs/images.html#static-image-resources

I thought it would be better.

**Comment by Creemli** [comment]
If we start a new project, we would better use "require".
But if we integrate with existing apps, maybe we need to copy the images from Native.
