### ISSUE TITLE
app not responding when copy pasting data in TextInput

### ISSUE THREAD

**Issue by chandu0101** [taobaofed/react-web#32]
Hi
       I have Custom TextInput component based on `TextInput` on  `onChangeText`  i have some validation logic to be executed and component updates its state with error messages if any.  If i manually type data then component updating its state fine, but when i copy paste data into TextInput app is not responding anymore. Chrome displaying alert saying page not responding do you want to kill/wait ..

**Comment by yuanyan** [comment]
We try to reappear this issue, could u provide the code?

**Comment by chandu0101** [comment]
my app written in scala.js ;) , i'll try to reimplement the same in js and then will post here.

**Comment by yuanyan** [comment]
Maybe fixed in https://github.com/taobaofed/react-web/commit/cc2ab4a98ac04af0e9e817d89e84c51d4252fa23

**Comment by chandu0101** [comment]
>Maybe fixed in cc2ab4a

Indeed , its working perfect now thanks alot :)
