### ISSUE TITLE
生成的react web希望支持directorjs路由

### ISSUE THREAD

**Issue by cgx9** [taobaofed/react-web#35]
习惯统一定义路由的方式，比如directorjs或者express的路由。
现在的react-web路由，我看是按点击某个记录或按钮顺序记录的。感觉使用directorjs的方式更直观与灵活。如果ios也能这样定义就好了。毕竟大部分的web框架都这种方式。

**Comment by yuanyan** [comment]
考虑在Navigator的基础上支持url参数触发路由

**Comment by akecn** [comment]
会不会导致与 React Native 的代码不一致呢？

**Comment by cgx9** [comment]
路由能独立配置的话，其实挺方便，比如某个路由使用不同的组件，在有平台要求时。做isormorphic时，服务端路由与客户端路由时分开配置的，这样比较灵活。

**Comment by yuanyan** [comment]
@cgx9 可以把你希望的方式拿出来讨论下

**Comment by cgx9** [comment]
@yuanyan 希望有个路由文件作为入口，这里，不同的平台有不同的路由文件（非平台相关的则作为一个公共的路由），跟平台相关的组件则在这里传入。
这样能尽量做到更大的复用。

**Comment by mrtone** [comment]
路由功能确实很希望能够有 :)  有计划添加支持吗？

**Comment by SidFeng** [comment]
作为一个手机web站点，比如我在app中分享出来的链接，是要进到某个具体页面的，而不是统一打开首页，这个怎么实现？

**Comment by huangzuizui** [comment]
我的产品中路由模块app和web平台的独立的，app中用的是[react-native-router-flux](https://github.com/aksonov/react-native-router-flux),    @@@web中用的是[react-router](https://github.com/reactjs/react-router)。其他containers的代码基本能跨平台公用，目前效果还不错，@cgx9 @mrtone 可以试试哈。另外淘宝团队是否有计划基于以上两个路由模块，开发一款通用的呢@yuanyan

**Comment by Shawn8585** [comment]
不知道现在支持固定路由了吗？现在我开发了一个微信公众号的web端，里面设计到微信支付，支付地址需要提前在公众号中配置。不知道现在的版本能满足我的需求吗？

**Comment by brainpoint** [comment]
react-native的navigator设计的并不好, 针对具体页面地址, 以及路由配置我写了一个, 结合react-router来做路由配置  -> [febs-react-component](https://github.com/brainpoint/febs-react-component)

目前还缺少多页面延迟加载的方式, 大家可以看下, 望指正.
