### ISSUE TITLE
display:flex is missing in CSS?

### ISSUE THREAD

**Issue by gre** [taobaofed/react-web#36]
Hi, first of all thanks for this great project :)

I have a View that uses this style:

```
{
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  }
```

but the DOM version don't have a `display:flex` required to make the other CSS properties to work.
Have you see this?

Thanks

**Comment by gre** [comment]
okay, so actually it is because I was not using react-web but react-dom.

It's not clear in the documentation how to work with react-dom, is it even compatible?

Is there a reason why we have to use `AppRegistry.registerComponent` and `AppRegistry.runApplication` but not `React.render` ? (according to UIExplorer example)

Why not doing like `react-dom` : exposing a render() function?

**Comment by xueduany** [comment]
@gre you need a compatible framework instead of pure react-native code, react-web is available for react-native code both compate with H5 platform, not complete compat. But react-mix is available for react-js code both compate with APP platform.Because it provide CSS function, Dom API .So that, remmend you to try react-mix framework , it satisfy  yours requirements.

**Comment by gre** [comment]
I'm not sure react-mix is what i'm looking for. I'm looking for a minimal react-native web implementation to be able to smoothly port things over web. react-web is just fine, it just looks like some build system are somehow required (for instance "webpack-html-plugin" is required, otherwise you fall again into the missing CSS problem )

**Comment by xueduany** [comment]
@gre if you want to translate react-native code into web, just I know, react-web is mostly compat basic react-native component API, but react-native still have some function by native code doing, you still have amount of jobs to continue doing, or help improving react-web js implement like my job.^_^

**Comment by chandu0101** [comment]
>It's not clear in the documentation how to work with react-dom, is it even compatible?

yeah its possible i am using ReactDOM.render only .. 

Sample code .. 

```
    ReactDOM.render(AdminRouter.router, dom.document.getElementById("app"))
```

and my index.html 

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>My App</title>
    <style>
        body {
            font-family: sans-serif;
        }

        .react-root {
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;

            box-sizing: border-box;
            display: -webkit-box;
            display: -webkit-flex;
            display: -ms-flexbox;
            display: flex;
            -webkit-box-orient: vertical;
            -webkit-box-direction: normal;
            -webkit-flex-direction: column;
            -ms-flex-direction: column;
            flex-direction: column;

        }
        .react-root .react-view {
            position: relative;

            box-sizing: border-box;
            display: -webkit-box;
            display: -webkit-flex;
            display: -ms-flexbox;
            display: flex;
            -webkit-box-orient: vertical;
            -webkit-box-direction: normal;
            -webkit-flex-direction: column;
            -ms-flex-direction: column;
            flex-direction: column;

        }

    </style>

</head>
<body>

<div id="app"  class="react-root"></div>

</body>
</html>
```

**Comment by gre** [comment]
好的，我会试试看。
谢谢 😂

**Comment by chandu0101** [comment]
没问题 :D
