### ISSUE TITLE
when using a non React Native component that uses `style` props, that object still get processed

### ISSUE THREAD

**Issue by gre** [taobaofed/react-web#37]
I'm trying to use `react-canvas` because I need to get things done with a Canvas but `react-web` breaks the library because it overrides all style props.

**What happens**: react-web overrides the style props. [see code here](https://github.com/taobaofed/react-web/blob/c664ce5f1aef1ff8b2501a1bcbe8de69668feb20/Libraries/StyleSheet/extendCreateElement.js)
**What** I think **should happens**: react-web should overrides `style` **only** if the  one of React Native component, not **ALL** components.

Also, [that ducktyping](https://github.com/taobaofed/react-web/blob/c664ce5f1aef1ff8b2501a1bcbe8de69668feb20/Libraries/StyleSheet/extendCreateElement.js#L13) is error prone: I think you should have an internal whitelist of all react-web components and just see if the `type` is in this list.

I'll try to fix it and provide a PR

**Comment by yuanyan** [comment]
That is a problem, react-web should not process all.
