### ISSUE TITLE
Module not found: Error: Cannot resolve module 'ReactView'

### ISSUE THREAD

**Issue by chandu0101** [taobaofed/react-web#4]
Hi,

here is my webpack config

```js
 plugins: [
        new HasteResolverPlugin({
            platform: 'web'
        }),
        new webpack.NoErrorsPlugin(),
        new CommonsChunkPlugin({
            name: "mainpage"
        })
    ],
    resolve: {
        alias: {
            'react-native': 'react-web'
        }
    },
```

but when i run webpack i am getting module not found for components/apis :s

`ERROR in ./~/react-web/lib/react-web.js
Module not found: Error: Cannot resolve module 'ReactTouchableOpacity' in admin/node_modules/react-web/lib
 @ ./~/react-web/lib/react-web.js 190:13-45
`

**Comment by yuanyan** [comment]
Bug with  Haste Resolver Plugin, will fix soon.

**Comment by chandu0101** [comment]
>Bug with Haste Resolver Plugin, will fix soon.

cool , looking forward too :)

**Comment by yuanyan** [comment]
@chandu0101 It work now

**Comment by chandu0101** [comment]
yeah its working fine now , thank you :)
