### ISSUE TITLE
making setNativeProps covering more cases

### ISSUE THREAD

**Issue by gre** [taobaofed/react-web#44]
Look in this Animated web implementation:

https://github.com/animatedjs/interactive-docs/blob/gh-pages/Animated.js#L955

they uses `React.CSSPropertyOperations.setValueForStyles` which allows to set a style. I think we need to use it with the internal react-web preprocessor instead of current setNativeProps implementation.

see also notes in https://github.com/gre/react-web/commit/91ab4100fbd81f49aced3ef151c63af8b324c2c0

**Comment by yuanyan** [comment]
Wrap setValueForStyles in setNativeProps now. https://github.com/taobaofed/react-web/blob/master/Libraries/Utilties/setNativeProps.web.js#L33

**Comment by gre** [comment]
I think you also need to call [extendProperties](https://github.com/taobaofed/react-web/blob/master/Libraries/StyleSheet/extendProperties.web.js) in order to get full React Native style feature (like transform style)
Also i'm not sure if the `convertTransform` is required now.

After that, we can enable back the Animated code (that I have commented out) and hopefully we should have functional and faster animations :)
