### ISSUE TITLE
support mousemove event in PanResponder

### ISSUE THREAD

**Issue by gre** [taobaofed/react-web#45]
https://github.com/taobaofed/react-web/blob/master/Libraries/PanResponder/injectResponderEventPlugin.web.js#L24

PanResponder move event is currently not supported via mouse events

**Comment by gre** [comment]
any idea why topMouseMove don't work ?

**Comment by yuanyan** [comment]
MouseMove is really different with touchmove.

**Comment by gre** [comment]
yeah I know it's tricky. Would React Responder code help for this? Do you have some plan to try to implement it soon? or do you want me to take a look (if so, any idea where to investigate / what to do ?)

Thanks
