### ISSUE TITLE
Uncaught TypeError: this.touchableGetInitialState is not a function

### ISSUE THREAD

**Issue by chandu0101** [taobaofed/react-web#50]
Hi,
     I just updated to 0.2.0 , i am getting following error 
`Uncaught TypeError: this.touchableGetInitialState is not a function` at this line https://github.com/taobaofed/react-web/blob/ed76ab8839c48f5efedfc7601bb79599831266ae/Libraries/Text/Text.web.js#L87

**Comment by yuanyan** [comment]
A publish build problem, fix in 0.2.1.

**Comment by chandu0101** [comment]
its working now thanks :)
