### ISSUE TITLE
ScrollView (ListView) 双指触控问题

### ISSUE THREAD

**Issue by mrtone** [taobaofed/react-web#51]
http://rawgit.com/taobaofed/react-web/master/pages/uiexplorer.html

iOS 设备上，列表页只要两个手指滑动，就会出现问题，Android 暂时没测试，可以体验一下～

**Comment by yuanyan** [comment]
已确认有此问题，修复中

**Comment by yuanyan** [comment]
Fixed in https://github.com/taobaofed/react-web/commit/cc2ab4a98ac04af0e9e817d89e84c51d4252fa23

**Comment by mrtone** [comment]
测试了一下，效果特别好 :)
