### ISSUE TITLE
Module not found和Module parse failed

### ISSUE THREAD

**Issue by maoyongming** [taobaofed/react-web#53]
初次接触这个项目，感觉蛮好的，Example都已经跑通；
但是在我们实际线上的项目使用react-web start的时候报错了
1、ERROR in ./common_modules/comkit/view-container.js
Module not found: Error: Cannot resolve module 'dismissKeyboard' in /Users/xx/react-native/app/common_modules/comkit
 @ ./common_modules/comkit/view-container.js 7:23-49
类似几个组件报错，Dimensions、dismissKeyboard、TextInputState、ProgressBarAndroid、SwitchAndroid、BackAndroid

2、ERROR in ./~/react-native-code-push/CodePush.js
Module parse failed: /Users/xx/react-native/d2papp/node_modules/react-native-code-push/CodePush.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import { AcquisitionManager as Sdk } from "code-push/script/acquisition-sdk";
| import { Alert } from "./AlertAdapter";
| import requestFetchAdapter from "./request-fetch-adapter";
 @ ./apps/app.js 21:15-48

ERROR in ./~/react-native-viewpager/ViewPager.js
Module parse failed: /Users/xx/react-native/d2papp/node_modules/react-native-viewpager/ViewPager.js Line 30: Unexpected token ...
You may need an appropriate loader to handle this file type.
|
|   propTypes: {
|     ...View.propTypes,
|     dataSource: PropTypes.instanceOf(ViewPagerDataSource).isRequired,
|     renderPage: PropTypes.func.isRequired,
 @ ./apps/guide/index.js 14:16-49
引用了一些外部组件解析的时候报错

还有一些其他问题都已解决，还剩下上面2种，望帮忙看下

**Comment by yuanyan** [comment]
跨平台的差异化是需要通过判断平台来解决的, 比如BackAndroid是Android下会应有的组件，其相关实现应封装在 `xx.android.js`下

**Comment by maoyongming** [comment]
主要我们的项目android和ios是在一个app文件下面的，项目结构

**Comment by maoyongming** [comment]
跨平台的差异化看来是需要判断不同平台引用不同的组件js来解决了；

类似Dimensions这类的Api可以支持吗
