### ISSUE TITLE
Unable to find react-web-cli

### ISSUE THREAD

**Issue by rreusser** [taobaofed/react-web#54]
The instructions for adding react-web to an existing project say to use `react-web-cli`, but that appears to create a new project, not add it to an existing project. I tried looking for the source, and get a 404 for [the github repo linked to](https://github.com/taobaofed/react-web-cli) from the [react-web-cli npm module](https://www.npmjs.com/package/react-web-cli). I can dig to find the source in my global node_modules, but it would be great if it were open-sourced!

Very exciting project though. Thanks for the hard work!

**Comment by yuanyan** [comment]
Sorry for not sync with npm. It has been moved in react-web: https://github.com/taobaofed/react-web/tree/master/react-web-cli

**Comment by rreusser** [comment]
No worries! Thanks so much!
