### ISSUE TITLE
Haste resolver does not resolve *.web.js

### ISSUE THREAD

**Issue by rreusser** [taobaofed/react-web#55]
I created a RN0.19 app and added react-web by running `react-web init` in a separate directory and copying in the dependencies and webpack config. You can see the full result at https://github.com/rreusser/react-web-sample-app.

**Expected behavior**:

For Android and iOS, `import App from './app/views/app'` imports `./app/views/app/index.${platform}.js`. I would expect that line to import `./app/views/app/index.web.js` for the web platform, or `./app/views/app.web.js` if not nested in a directory.

**Observed behavior**:

Files with suffix `*.web.js` are not built (excluding the entry point `index.web.js` which is explicitly specified). `react-web start` gives the error:

```
ERROR in ./index.web.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./app/views/app in /Users/rreusser/path/to/SampleApp
 @ ./index.web.js 11:19-45
```

I can work around this by using `*.js` instead of `*.web.js` for the web platform, i.e.:
- `app/views/app/index.ios.js` (imported by iOS)
- `app/views/app/index.android.js` (imported by Android)
- `app/views/app/index.js` (imported by web and fortunately not by the others)

In this case, I do see the resolver line:

```
  [242] ./app/views/app/index.js 4.42 kB {0} [built]
```

I'd prefer to call it `index.web.js` though. I got as far as starting to work through [haste-resolver](https://github.com/yuanyan/haste-resolver) and [haste-resolver-webpack-plugin](https://github.com/yuanyan/haste-resolver-webpack-plugin) before deciding to see if this should be expected to work. I think it's just a config issue, but I'm not quite able to solve it.

Any advice would be greatly appreciated!

Thanks!

**Comment by yuanyan** [comment]
Should make hated-resolver sync with react-native.

**Comment by rreusser** [comment]
Makes sense. Yeah, looked like they'd diverged a bit. It also felt like a usage issue on my part but nothing was jumping out.

**Comment by brianneisler** [comment]
Any progress on this issue? I'm seeing the same on my end

**Comment by flyskywhy** [comment]
@rreusser @yuanyan @brianneisler , #165 resolved this issue
