### ISSUE TITLE
react web 的 providesModule 与 react native 的对应不起来

### ISSUE THREAD

**Issue by yujiangshui** [taobaofed/react-web#58]
react web ：https://github.com/taobaofed/react-web/blob/master/Libraries%2FText%2FText.web.js#L7

react native：https://github.com/facebook/react-native/blob/master/Libraries/Text/Text.js#L9

这样在通过 haste 方式引入组件时，代码不能同时跑在 Native 或者 Web 端，肯定有一端会报错 `Cannot resolve module`。

是有意为之的吗？

**Comment by yuanyan** [comment]
在React native里不要直接通过require('Text') 方式引入，全部通过React-native包暴露的接口方式引用：
```
var {Text} = require('react-native');
```

**Comment by yujiangshui** [comment]
那对于一个组件 Aa.jsx 中有引入一个基础组件 Text，它同时被 index.ios.js 和 index.web.js 引入做初始化，那在 Aa.jsx 里面如何使用 Haste 方式加载组件呢？

要判断 Platform 然后用不同的加载方式？

```
if (Platform.OS === 'web') {
  var Text = require('ReactText');
} else if (Platform.OS === 'ios') {
  var {Text} = require('react-native');
}
```

**Comment by yuanyan** [comment]
Haste 方式不要尽量在应用代码里使用

**Comment by yujiangshui** [comment]
没太明白，Haste 方式可以用在哪些场景中？还是废弃掉不用了？

**Comment by yujiangshui** [comment]
没太明白，Haste 方式可以用在哪些场景中？还是废弃掉不用了？

**Comment by yuanyan** [comment]
Haste只是在React web 或者在App内使用，避免在App引用React Web使用Haste方式
