### ISSUE TITLE
Split cli / webserver and core libraries into separate packages

### ISSUE THREAD

**Issue by keeth** [taobaofed/react-web#61]
I'd like to depend on a package that contains just component libs and their runtime dependencies, not babel, webpack, etc.

Would it be possible to split out the core libaries (everything under Libraries/) as it's own package?

Thanks!

**Comment by pmead** [comment]
@keeth something like this would be good.

I've run into problems withthe version of `babel-core` react-web uses. Its older than the react-core used by react-native and my project so the .babelrc used to run my jest tests breaks react-web.
