### ISSUE TITLE
Problem with escope dependency

### ISSUE THREAD

**Issue by Tiagojdferreira** [taobaofed/react-web#63]
Just cloned your repo and after doing ```npm install``` and ```npm start``` I got an issue with 'visitClass' which is caused by the library escope. For more info, read https://github.com/babel/babel-eslint/issues/243 , but the basic work around is:
```
npm uninstall escope@3.4.0
npm install escope@3.3.0
```
This fixes it the problem, but I am not sure if this should be added to the readme, as they seem to be working on a solution and the problem might be fixed by updating babel-eslint in the near future.

**Comment by yuanyan** [comment]
Expect upgrade the version of the babel-eslint.

**Comment by yuanyan** [comment]
PR：https://github.com/taobaofed/react-web/pull/68 fix this issues.
