### ISSUE TITLE
Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by chenchen1008** [taobaofed/react-web#71]
when I run the UIexplorer  examples，I meet the error。

`UIExplorerBlock.js:28  Uncaught TypeError: Cannot read property 'string' of undefined`

package.json

{
  "name": "UIExplorerApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start"
  },
  "dependencies": {
    "react": "0.14.7",
    "react-dom": "^0.14.7",
    "react-web": "^0.2.1"
  },
  "devDependencies": {
    "babel": "5.8.19",
    "babel-core": "5.8.19",
    "babel-loader": "^6.2.4",
    "haste-resolver-webpack-plugin": "^0.2.1",
    "json-loader": "^0.5.4",
    "react-hot-loader": "^1.3.0",
    "react-native-cli": "^0.1.10",
    "webpack": "^1.12.14",
    "webpack-dev-server": "^1.14.1",
    "webpack-html-plugin": "^0.1.1"
  }
}

**Comment by cssivision** [comment]
use fixed react react-dom version to fix this, fixed on https://github.com/taobaofed/react-web/pull/224
