### ISSUE TITLE
如何将打包体积缩小？

### ISSUE THREAD

**Issue by lucianlo** [taobaofed/react-web#75]
webpack 以及其他的支持 CommonJS 规范的打包工具，都会把文件中 require 的所有组件都打包在一起。对于 React Native 来说代码体积大小无关紧要，而在 Mobile web 来说，就要稍微重要一些了。特别是如果你的项目只需要 Text 组件，但由于 require('react-web') 结果把所有的组件全部打包进来了，就比较伤感。

基于 webpack 插件，还可以用另一种方式引入组件以解决这个问题，你可以叫它 Haste 方式。使用这种方式需要加载 webpack 插件 haste-resolver-webpack-plugin，默认的 webpack 配置已经帮你加载好了，你可以直接在组件里面这样用：

var Text = require('ReactText');
而不是以前那样：

var {Text} = require('react-native');

关于这个内容，能否详细告知一下，我生成最简单的react-native的项目，加入react-web后，对项目打包，生成的bundlejs为4M,bundlemap为6M，怎么破

**Comment by yuanyan** [comment]
如果在意包大小，目前是通过别名方式按需引入组件

**Comment by SaberLu** [comment]
@yuanyan 恕我愚钝，没有非常深入去学习.....我想知道，我如何知道react-native的别名呢？
如你所示：var Text = require('ReactText');
那我的想法？var Compoent= require('ReactCompoent');

这样吗？还是说是别的？哪里可以找到详细的描述呢？

**Comment by yuanyan** [comment]
对应关系: https://github.com/taobaofed/react-web#components
