### ISSUE TITLE
Issue upgrading from 0.1.6

### ISSUE THREAD

**Issue by gre** [taobaofed/react-web#77]
upgrading from 0.1.6 to 0.2.4.
If I try to `console.log("RN", require("react-native"));` I have:

<img width="1046" alt="screen shot 2016-03-14 at 12 29 36" src="https://cloud.githubusercontent.com/assets/211411/13743183/8b9c1aca-e9e0-11e5-85db-2a56d7198b0e.png">

which is weirdly the package.json content of react-web and not anymore the library content.

I didn't change anything in my webpack, do you have a hint on what happen/what I missed to change?

**Comment by gre** [comment]
for some reason, the "main" field of package.json is not resolved my webpack.

Because even if I do:
`console.log("RN", require("react-web"));`

there is the same bug.

If I do this:

```
  resolve: {
    alias: {
      "react-native": "react-web/lib/react-web.js"
    },
```

it works...

**Comment by mkraynov** [comment]
Same problem :(

**Comment by mkraynov** [comment]
Rolling back to "haste-resolver-webpack-plugin": "^0.1.2" resolved this problem for me
