### ISSUE TITLE
Error when selecting an item in a picker

### ISSUE THREAD

**Issue by kkjamie** [taobaofed/react-web#79]
`invariant.js:39 Uncaught Invariant Violation: Ended a touch event which was not counted in trackedTouchCount.`

This breaks all other interactions, buttons etc.

Reproducible in the UIExplorer

**Comment by kkjamie** [comment]
I have done some more investigation. The problem is not equal in all browsers, It seems chrome is the culprit. `<select>` and `<option>` elements don't dispatch events for mousedown, but do for mouseup. breaking react's ResponderEventPlugin. I have tried several workarounds but nothing works so far, I may have to make my own drop down component that doesn't use `<select>` or `<option>`

**Comment by yuanyan** [comment]
If the problem is reproduce we will reopen issue.
