### ISSUE TITLE
iOS 系统 ListView 滚动时，会误触 item 的 onPress 事件

### ISSUE THREAD

**Issue by mrtone** [taobaofed/react-web#82]
印象中，之前的版本是没有这个问题的，多滑动两下即可测出问题规律。
http://rawgit.com/taobaofed/react-web/master/pages/uiexplorer.html

**Comment by follyxing** [comment]
+1

**Comment by dioxide** [comment]
+1

**Comment by huangzuizui** [comment]
该问题在我的产品中也比较严重，突出。不知道淘宝团队什么时候解决哈。很期待啊，不然web平台体验差，没法应用到生产环境。 @yuanyan

**Comment by Curtaing** [comment]
+1
