### ISSUE TITLE
scripts/publish inconsistent 

### ISSUE THREAD

**Issue by mvayngrib** [taobaofed/react-web#84]
i was playing with DatePickerIOS and when building, I see some differences, for example react-web.js looks like this instead of the way you have it published:

```js
...
var _react2 = _interopRequireDefault(_react);
var _ReactStyleSheet = require('StyleSheet/StyleSheet.web');
var _ReactStyleSheet2 = _interopRequireDefault(_ReactStyleSheet);
var _ReactActivityIndicator = require('ActivityIndicator/ActivityIndicator.web');
var _ReactActivityIndicator2 = _interopRequireDefault(_ReactActivityIndicator);
var _ReactDrawerLayout = require('DrawerLayout/DrawerLayout.web');
var _ReactDrawerLayout2 = _interopRequireDefault(_ReactDrawerLayout);
...
```

Could it be picking up some options from a global babel installation?

**Comment by vmakhaev** [comment]
Confirm same problem.

**Comment by vmakhaev** [comment]
@yuanyan could you look at your global .babelrc files or maybe something else? This issue makes impossible building the project and blocks contributing.

**Comment by yuanyan** [comment]
@vmakhaev Eslint issue fixed.
