### ISSUE TITLE
react-web init <ProjectDir>  误解 ？

### ISSUE THREAD

**Issue by febobo** [taobaofed/react-web#85]
如题 react-web init <ProjectDir>   在已有的白rn项目下使用项目目录会抱错

```
   react-web init ~/Documents/react/demo/demo/ysApp   
"/Users/febobo/Documents/react/demo/demo/ysApp" is not a valid name for a project. Please use a valid identifier name (alphanumeric).
```

使用 react-web init <name> 会生成一个新项目 ， 感觉这个参数模凌两可 ， 有误解的成份

**Comment by yuanyan** [comment]
建议是？

**Comment by warmhug** [comment]
`Installing react-web package from npm...` 写死不太好，npm install 不用代理会很慢的

**Comment by yuanyan** [comment]
@warmhug OK，下一版本里会支持参数传入

**Comment by Arguiwu** [comment]
现在支持参数传入没？ Installing react-web package from npm...   一直卡在这  半小时了

**Comment by flyskywhy** [comment]
@febobo ，你那个错误的原因是路径 / 符号引起的。react-native init 也是这样的参数，习惯了就没有误解了:P。只需要这样即可：

    cd ~/Documents/react/demo/demo/
    react-web init ysApp

**Comment by flyskywhy** [comment]
@warmhug @Arguiwu ，最新的代码已经可以不用 npm 而是直接使用 github.com/taobaofed/react-web.git ，所以就不用管 npm 卡死的问题了。

在目前 @yuanyan 还没有在 npm 上发布新版（>0.0.3） react-web-cli 的情况下，你们可以先手动修改 <node 安装目录>/lib/node_modules/react-web-cli/index.js 成 #154 中的样子，然后就可以使用 --version 参数来下载 github 上的代码了：

    react-web init --version git+https://github.com/taobaofed/react-web.git
