### ISSUE TITLE
Image引用本地图片会报错

### ISSUE THREAD

**Issue by cnsnake11** [taobaofed/react-web#86]
只要有本地图片引用，比如：
`<Image style={{width: 220, height: 170, }}  source={require('./img/fetch_error.png')} />
`

编译会报错：
ERROR in ./bbt-react-native/views/FetchError/img/fetch_error.png
Module parse failed: /Users/babytree-mbp13/projects/xcodeProjects/rnweb/bbt-react-native/views/FetchError/img/fetch_error.png Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./bbt-react-native/views/FetchError/FetchError.js 61:24-56

rn版本0.20.0，reactweb版本0.2.4

谢谢回复。

**Comment by Tiagojdferreira** [comment]
Have you tried adding file-loader to your webpack build ?
Do:
```
npm install --save file-loader
```
And add:
```
{
        test: /\.(eot|otf|svg|ttf|woff|woff2|png|jpg|gif)\w*/,
        loader: 'file'
      }
```
To your webpack.config.js

**Comment by cnsnake11** [comment]
thank you for your reply, @Tiagojdferreira .but i think this should be ready in react-web.

i will try it out follow your way,thanks.

**Comment by fov42550564** [comment]
有没有试？有用没有

**Comment by cnsnake11** [comment]
不好意思，还没有试呢。。。

**Comment by fov42550564** [comment]
我试过了，可以的，但是建议设置为默认配置

**Comment by yujiangshui** [comment]
@cnsnake11 如果没啥问题了，可以吧 issue close 掉。
