### ISSUE TITLE
DrawerLayout overlay problem

### ISSUE THREAD

**Issue by vmakhaev** [taobaofed/react-web#89]
While trying to use DrawerLayout met a problem, which can be separated in two parts:
1) [overlay](https://github.com/taobaofed/react-web/blob/master/Libraries/DrawerLayout/DrawerLayout.web.js#L115) has an [absolute positioning](https://github.com/taobaofed/react-web/blob/master/Libraries/DrawerLayout/DrawerLayout.web.js#L262-L266) and covers all [content](https://github.com/taobaofed/react-web/blob/master/Libraries/DrawerLayout/DrawerLayout.web.js#L112), which makes content unresponsible to user actions.
2) [drawer](https://github.com/taobaofed/react-web/blob/master/Libraries/DrawerLayout/DrawerLayout.web.js#L116) itself is open from very beginning, while [openValue](https://github.com/taobaofed/react-web/blob/master/Libraries/DrawerLayout/DrawerLayout.web.js#L77) is initially set to 0. Probably this is connected to Animated.View, which I did not dig in.

There is an [example](https://github.com/vmakhaev/react-web-drawer-overlay-bug) that reproduces the problem. Let me know if you need anything else.

BTW, thanks for all your work on react-web, which is awesome

**Comment by yuanyan** [comment]
Need a drawer without overlay?
