### ISSUE TITLE
uc浏览器ios 问题

### ISSUE THREAD

**Issue by zhang314494734** [taobaofed/react-web#92]
ios 版本的uc浏览器显示不出页面，实例中只显示出来标题。

**Comment by yuanyan** [comment]
能提供更详细的信息吗

**Comment by zhang314494734** [comment]
![image](https://cloud.githubusercontent.com/assets/5069345/14782268/dae465be-0b1a-11e6-8ef2-fbe6e6dbae89.png)

这是我在iphone6s 上使用uc浏览器打开的UIExploer的实例，我自己的项目是空白页

**Comment by yuanyan** [comment]
看下用最新的0.3版本是否ok？

**Comment by lijax** [comment]
UC安卓上调试`Uncaught SyntaxError: Unexpected token {`

截图如下，箭头函数不支持？

![1367dd10-3e28-4d70-b8f9-d32a24addd19](https://cloud.githubusercontent.com/assets/1861654/16480036/8e07dd76-3ed6-11e6-8261-cad01c167ed3.png)

**Comment by yuanyan** [comment]
@lijax 看问题应该是编译问题，这个箭向函数为什么没有被编译呢?

**Comment by lijax** [comment]
@yuanyan 这个是原生端的模块，本来是根据Platform来动态require模块的，在其他浏览器没出现问题，UC就出现这个问题。看来放在if里面require虽然可以解决编译时报错问题，但是模块还是会打包进来，只是压根就没编译而已。

现在问题已经解决，把用到这个模块的界面单独写了web端的实现，然后在webpack里面去替换加载（webpack.NormalModuleReplacementPlugin）。
