### ISSUE TITLE
Not working with redux-persist

### ISSUE THREAD

**Issue by Tiagojdferreira** [taobaofed/react-web#94]
I have been developing a small app https://github.com/Tiagojdferreira/ryuutama . Recently I decided to add react-web and it seemed fine, but I just realized that redux actions are not working.

It seems the problem comes from me using redux-persist.
Not sure if the problem comes from redux-persist or react-web, so I will open this problem on their repo as well.

Updating redux-persist makes the app work again, but I cant persist or recover the state

**Comment by yuanyan** [comment]
Is there more information why not work with redux-persist？

**Comment by rt2zz** [comment]
It appears the rehydrate action is not firing.Possobly related to the AsyncStorage implementation.

**Comment by rt2zz** [comment]
fix here: https://github.com/taobaofed/react-web/pull/96
