### ISSUE TITLE
require file by platform

### ISSUE THREAD

**Issue by fov42550564** [taobaofed/react-web#95]
Test.ios.js   Test.web.js   Test.android.js
require('./Test')
in react-native, on android require is Test.android.js, on ios require is Test.ios.js
how to require Test.web.js in react-web?

**Comment by vmakhaev** [comment]
If you use webpack, there is [haste-resolver-webpack-plugin plugin](https://github.com/yuanyan/haste-resolver-webpack-plugin) for this

**Comment by fov42550564** [comment]
how to use it? can you give me a example please?

**Comment by brianneisler** [comment]
The plugin seems to be broken as of right now. Using it on the latest version causes a strange import issue yuanyan/haste-resolver-webpack-plugin#1

**Comment by flyskywhy** [comment]
@fov42550564 , PR #165 resolved this issue

@brianneisler , the plugin issue https://github.com/yuanyan/haste-resolver-webpack-plugin/issues/1 seems fixed
